# syntax=docker/dockerfile:1.7
# Generated by vibrate test-1.0 — do not edit by hand.
#
# Harness:  codex (OpenAI Codex)
# Profile:  backend
# Shell:    zsh
# Features: python,go,node,postgres-client,gh,ralphex
# Extensions:  (none)
#
# Reproduce this Dockerfile with:
#   vibrate build-dockerfile --harness=codex --profile=backend --shell=zsh

# ============================================================================
# Stage 1 — base: Ubuntu 24.04 LTS + always-on substrate
# ============================================================================
FROM ubuntu:24.04 AS base

ENV DEBIAN_FRONTEND=noninteractive

# Apt cache layer — always-on CLIs that every profile gets. Kept small.
RUN apt-get update && apt-get install -y --no-install-recommends \
      ca-certificates curl wget \
      git gpg openssh-client \
      sudo vim less tree \
      jq sqlite3 dnsutils \
      unzip xz-utils \
      build-essential \
      locales \
      zsh \
 && locale-gen en_US.UTF-8 \
 && rm -rf /var/lib/apt/lists/*

# --- shell rc files (copied into new-user homes via /etc/skel) ---
COPY shells/bashrc /etc/skel/.bashrc
COPY shells/zshrc /etc/skel/.zshrc
RUN mkdir -p /etc/skel/.config/fish
COPY shells/config.fish /etc/skel/.config/fish/config.fish

# --- shell-agnostic welcome banner (sourced from each rc file) ---
RUN mkdir -p /opt/vibrator
COPY scripts/welcome.sh /opt/vibrator/welcome.sh
RUN chmod 0755 /opt/vibrator/welcome.sh

# Mirror rc files into /root/ so root sub-invocations (debugging via
# 'docker exec -u root') get the same prompt + banner, and so zsh
# build-stage commands don't trip zsh-newuser-install.
RUN cp /etc/skel/.bashrc /root/.bashrc \
 && cp /etc/skel/.zshrc /root/.zshrc \
 && mkdir -p /root/.config/fish \
 && cp /etc/skel/.config/fish/config.fish /root/.config/fish/config.fish

ENV LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 COLORTERM=truecolor

# uv tools install into /usr/local/bin so every user finds them on PATH.
ENV UV_TOOL_BIN_DIR=/usr/local/bin

# ripgrep — multi-arch binary release. Always-on.
RUN ARCH=$(dpkg --print-architecture) && \
    RG_VERSION="15.1.0" && \
    if [ "$ARCH" = "amd64" ]; then RG_TRIPLE="x86_64-unknown-linux-musl"; else RG_TRIPLE="aarch64-unknown-linux-gnu"; fi && \
    curl -fsSL "https://github.com/BurntSushi/ripgrep/releases/download/${RG_VERSION}/ripgrep-${RG_VERSION}-${RG_TRIPLE}.tar.gz" \
      -o rg.tar.gz && \
    tar -xzf rg.tar.gz --strip-components=1 -C /usr/local/bin/ "ripgrep-${RG_VERSION}-${RG_TRIPLE}/rg" && \
    rm rg.tar.gz && rg --version

# fd-find via apt (Ubuntu names the binary fdfind; we symlink to fd).
RUN apt-get update && apt-get install -y --no-install-recommends fd-find fzf \
 && ln -sf /usr/bin/fdfind /usr/local/bin/fd \
 && rm -rf /var/lib/apt/lists/*

# ============================================================================
# Stage 2 — features
# ============================================================================
FROM base AS features

# --- feature: python (Python 3.13) ---
# uv (Python package manager) is the installer for Python itself.
# Install it system-wide so later RUN steps in features that depend on
# Python ("uv tool install ...") all share the same uv binary.
RUN curl -LsSf --retry 3 --retry-delay 5 --retry-all-errors https://astral.sh/uv/install.sh \
      | UV_INSTALL_DIR=/usr/local/bin sh \
 && uv --version
RUN uv python install 3.13 \
 && ln -sf "$(uv python find 3.13)" /usr/local/bin/python3.13 \
 && update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.13 100 \
 && python3 --version

# --- feature: go (Go toolchain) ---
COPY --from=golang:1.26.2 /usr/local/go /usr/local/go
ENV PATH="/usr/local/go/bin:${PATH}"
RUN go version

# --- feature: node (Node.js + Bun) ---
COPY --from=oven/bun:1 /usr/local/bin/bun /usr/local/bin/bun
COPY --from=node:22-bookworm-slim /usr/local/bin/node /usr/local/bin/node
COPY --from=node:22-bookworm-slim /usr/local/lib/node_modules /usr/local/lib/node_modules
RUN ln -sf /usr/local/lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npm \
 && ln -sf /usr/local/lib/node_modules/npm/bin/npx-cli.js /usr/local/bin/npx \
 && node --version && npm --version && bun --version

# --- feature: postgres-client (Postgres client) ---
RUN apt-get update && apt-get install -y --no-install-recommends postgresql-client \
 && rm -rf /var/lib/apt/lists/* \
 && psql --version

# --- feature: gh (GitHub CLI) ---
RUN curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg \
      | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
 && chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
 && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" \
      | tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
 && apt-get update && apt-get install -y --no-install-recommends gh \
 && rm -rf /var/lib/apt/lists/* \
 && gh --version

# --- feature: ralphex (ralphex) ---
RUN ARCH=$(dpkg --print-architecture) && \
    RALPHEX_VERSION="1.0.1" && \
    curl -fsSL --retry 3 --retry-delay 5 \
      "https://github.com/umputun/ralphex/releases/download/v${RALPHEX_VERSION}/ralphex_${RALPHEX_VERSION}_linux_${ARCH}.tar.gz" \
      -o ralphex.tar.gz && \
    tar -xzf ralphex.tar.gz && \
    mv ralphex /usr/local/bin/ && chmod +x /usr/local/bin/ralphex && \
    rm ralphex.tar.gz && \
    ralphex --version

# --- user creation + USER switch -------------------------------------------
# Build args supply the host's UID/GID so file permissions on bind-mounted
# workspace paths match the caller (set by internal/docker at build time).
ARG USERNAME=vibrate
ARG HOST_UID=1000
ARG HOST_GID=1000

# Replace any existing user/group at the target UID/GID (Ubuntu ships an
# "ubuntu" user at 1000 which usually clashes with the host's first user).
RUN set -eux; \
    if EXISTING_USER=$(getent passwd ${HOST_UID} | cut -d: -f1); [ -n "$EXISTING_USER" ]; then userdel -r "$EXISTING_USER" 2>/dev/null || true; fi; \
    if EXISTING_GROUP=$(getent group ${HOST_GID} | cut -d: -f1); [ -n "$EXISTING_GROUP" ]; then groupdel "$EXISTING_GROUP" 2>/dev/null || true; fi; \
    groupadd -g ${HOST_GID} ${USERNAME} && \
    useradd -m -s /bin/zsh -u ${HOST_UID} -g ${HOST_GID} ${USERNAME} && \
    echo "${USERNAME} ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/${USERNAME} && \
    chmod 0440 /etc/sudoers.d/${USERNAME}

USER ${USERNAME}
WORKDIR /home/${USERNAME}

# ============================================================================
# INVARIANT — install-destination ENVs at the privilege boundary
# ============================================================================
# The USER switch above is a privilege boundary. ENVs set in Stages 1-2
# (as root) PERSIST into Stages 3-5 (as the unprivileged user). Any ENV
# that directs a tool to install into a system path (e.g.
# UV_TOOL_BIN_DIR=/usr/local/bin) becomes a guaranteed EACCES once an
# extension in Stage 4 invokes that tool — because the user can't write
# to system paths.
#
# Every ENV that controls "where do binaries land" MUST be overridden
# here to point at a user-writable location. Common offenders:
#   - NPM_CONFIG_PREFIX     (npm install -g)
#   - UV_TOOL_BIN_DIR       (uv tool install)
#   - GOBIN                 (go install)  — not currently set; document
#   - CARGO_HOME            (cargo install) — not currently set; document
#   - GEM_HOME / GEM_PATH   (gem install) — not currently set; document
#   - PIP_TARGET            (pip install --target) — not currently set
#
# If you add a new "install dir" ENV to Stage 1 (base) or Stage 2
# (features), add a matching override here. Failure mode: an extension
# install in Stage 4 hits "Permission denied" on a /usr/local/* path.

# npm — global installs to ~/.npm-global (created by npm on first use).
ENV NPM_CONFIG_PREFIX=/home/${USERNAME}/.npm-global

# uv — tool symlinks to ~/.local/bin (overriding the /usr/local/bin set
# in Stage 1 which is correct only for the root-stage uv tool installs
# in features like audit-toolkit).
ENV UV_TOOL_BIN_DIR=/home/${USERNAME}/.local/bin

# Final image-wide PATH. Order:
#   1. user-local npm globals (mcp-server-*)
#   2. user-local uv tool symlinks + claude.ai install ($HOME/.local/bin)
#   3. /usr/local/go/bin (no-op if go feature wasn't selected — a
#      non-existent PATH entry is silently ignored by exec lookups)
#   4. system defaults
# We re-emit the whole PATH rather than $PATH-prepending because
# Docker's ENV var substitution only sees prior ENVs from THIS
# Dockerfile, and the base PATH lives in the ubuntu:24.04 image's
# default — invisible to the substitution.
ENV PATH=/home/${USERNAME}/.npm-global/bin:/home/${USERNAME}/.local/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# ============================================================================
# Stage 3 — harness install
# ============================================================================
FROM features AS harness

# --- harness: codex (OpenAI Codex) ---
RUN npm install -g @openai/codex \
 && codex --version

# ============================================================================
# Stage 4 — extensions
# ============================================================================
FROM harness AS extensions

# (no extensions selected)

# ============================================================================
# Stage 5 — runtime: labels, default command
# (User creation + USER switch already happened at end of Stage 2.)
# ============================================================================
FROM extensions AS runtime

# Auth env vars expected by this harness (forwarded by `docker run -e`):
ENV OPENAI_API_KEY=""

# Variant metadata — readable from inside the container.
ENV VIBRATOR_PROFILE="backend"
ENV VIBRATOR_FEATURES_LIST="python,go,node,postgres-client,gh,ralphex"
ENV VIBRATOR_EXTENSIONS_LIST="(none)"
ENV VIBRATOR_VERSION="test-1.0"

# Labels — used by `vibrate variants list` and upgrade workflows.
LABEL vibrator.version="test-1.0"
LABEL vibrator.harness="codex"
LABEL vibrator.profile="backend"
LABEL vibrator.shell="zsh"
LABEL vibrator.features="python,go,node,postgres-client,gh,ralphex"
LABEL vibrator.extensions="(none)"

CMD ["/bin/zsh"]
