package migrate

import (
	"reflect"
	"strings"
	"testing"
)

func TestParseDotenv_BasicLines(t *testing.T) {
	got, err := ParseDotenv(strings.NewReader(`# comment
HARNESS=claude-code
PROFILE=full
EMPTY=
`))
	if err != nil {
		t.Fatalf("ParseDotenv: %v", err)
	}
	want := []KV{
		{"HARNESS", "claude-code"},
		{"PROFILE", "full"},
		{"EMPTY", ""},
	}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("got %v, want %v", got, want)
	}
}

func TestParseDotenv_StripsExport(t *testing.T) {
	got, _ := ParseDotenv(strings.NewReader(`export HARNESS=claude-code`))
	if len(got) != 1 || got[0].Key != "HARNESS" {
		t.Errorf("export prefix not stripped: %v", got)
	}
}

func TestParseDotenv_UnquotesMatchingQuotes(t *testing.T) {
	cases := map[string]string{
		`X="hello world"`: "hello world",
		`X='it'`:          "it",
		`X=plain`:         "plain",
		`X="mismatched'`:  `"mismatched'`, // unchanged — quotes don't match
		`X=""`:            "",
	}
	for in, wantVal := range cases {
		got, _ := ParseDotenv(strings.NewReader(in))
		if len(got) != 1 {
			t.Errorf("input %q produced %d entries", in, len(got))
			continue
		}
		if got[0].Value != wantVal {
			t.Errorf("input %q → value %q, want %q", in, got[0].Value, wantVal)
		}
	}
}

func TestParseDotenv_SkipsMalformedLines(t *testing.T) {
	got, _ := ParseDotenv(strings.NewReader(`HARNESS=ok
no-equals-here
=no-key
ANOTHER=fine
`))
	want := []KV{{"HARNESS", "ok"}, {"ANOTHER", "fine"}}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("got %v, want %v", got, want)
	}
}

func TestToPin_MapsCoreFields(t *testing.T) {
	kvs := []KV{
		{"HARNESS", "claude-code"},
		{"PROFILE", "full"},
		{"SHELL", "zsh"},
		{"WITH", "playwright,audit-toolkit"},
		{"NO", "aider"},
		{"CATALOG", "claude-mem,context7"},
	}
	pin, notes := ToPin(kvs)

	if pin.Harness != "claude-code" || pin.Profile != "full" || pin.Shell != "zsh" {
		t.Errorf("core scalars wrong: %+v", pin)
	}
	if !reflect.DeepEqual(pin.With, []string{"playwright", "audit-toolkit"}) {
		t.Errorf("WITH parse wrong: %v", pin.With)
	}
	if !reflect.DeepEqual(pin.No, []string{"aider"}) {
		t.Errorf("NO parse wrong: %v", pin.No)
	}
	if !reflect.DeepEqual(pin.Extensions, []string{"claude-mem", "context7"}) {
		t.Errorf("CATALOG parse wrong: %v", pin.Extensions)
	}
	if len(notes) != len(kvs) {
		t.Errorf("expected one note per input key, got %d / %d", len(notes), len(kvs))
	}
}

func TestToPin_MapsClaudeMemPrereqs(t *testing.T) {
	kvs := []KV{
		{"CLAUDE_MEM_SERVER_BETA_API_KEY", "cmem_abc"},
		{"CLAUDE_MEM_SERVER_BETA_TEAM_ID", "team-1"},
		{"CLAUDE_MEM_SERVER_BETA_PROJECT_ID", "proj-1"},
	}
	pin, _ := ToPin(kvs)
	p, ok := pin.Prereqs["claude-mem-server-beta"]
	if !ok {
		t.Fatalf("prereqs.claude-mem-server-beta missing")
	}
	if p["api_key"] != "cmem_abc" || p["team_id"] != "team-1" || p["project_id"] != "proj-1" {
		t.Errorf("prereq values wrong: %v", p)
	}
}

func TestToPin_UnknownKeysGoToEnv(t *testing.T) {
	pin, notes := ToPin([]KV{
		{"OPENAI_API_KEY", "sk-test"},
		{"MY_CUSTOM_VAR", "x"},
	})
	if pin.Env["OPENAI_API_KEY"] != "sk-test" {
		t.Errorf("OPENAI_API_KEY should be preserved in [env], got %v", pin.Env)
	}
	if pin.Env["MY_CUSTOM_VAR"] != "x" {
		t.Errorf("MY_CUSTOM_VAR should be preserved in [env], got %v", pin.Env)
	}
	// Notes should mention "preserved verbatim".
	joined := strings.Join(notes, "\n")
	if !strings.Contains(joined, "preserved verbatim") {
		t.Errorf("expected verbatim-preservation note, got %s", joined)
	}
}

func TestToPin_UsernameIsDropped(t *testing.T) {
	pin, notes := ToPin([]KV{{"USERNAME", "old-user"}})
	// USERNAME has no dedicated pin field anymore — it's a build flag.
	if pin.Env["USERNAME"] != "" {
		t.Errorf("USERNAME should not be preserved under [env], got %v", pin.Env)
	}
	joined := strings.Join(notes, "\n")
	if !strings.Contains(joined, "ignored") {
		t.Errorf("expected ignored note for USERNAME, got %s", joined)
	}
}

func TestSplitCommaList_TrimsAndDropsEmpties(t *testing.T) {
	got := splitCommaList(" a, b ,  ,c, ")
	want := []string{"a", "b", "c"}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("got %v, want %v", got, want)
	}
	if splitCommaList("") != nil {
		t.Errorf("empty string should return nil")
	}
}

func TestRealisticVbEnvFile(t *testing.T) {
	// Mirror the structure of the user's actual .vb.env (sanitized).
	input := `# vibrator project pin — generated by interactive menu
# Edit by hand or re-run vibrate.
PROFILE=full
NO=aider

# claude-mem (auto-bootstrapped ... by vibrator)
CLAUDE_MEM_SERVER_BETA_API_KEY=cmem_864edc435eec72860a51c6fae5c3d999c6f3eceeb0ac8578
CLAUDE_MEM_SERVER_BETA_TEAM_ID=63d75e4d-835a-4843-95c4-2580a5678ecf
CLAUDE_MEM_SERVER_BETA_PROJECT_ID=469bf5e5-e852-499e-bdc0-66eb5ccfd910
`
	kvs, err := ParseDotenv(strings.NewReader(input))
	if err != nil {
		t.Fatalf("ParseDotenv: %v", err)
	}
	pin, _ := ToPin(kvs)

	if pin.Profile != "full" {
		t.Errorf("Profile = %q", pin.Profile)
	}
	if !reflect.DeepEqual(pin.No, []string{"aider"}) {
		t.Errorf("No = %v", pin.No)
	}
	cm := pin.Prereqs["claude-mem-server-beta"]
	if cm == nil || cm["api_key"] == "" || cm["team_id"] == "" || cm["project_id"] == "" {
		t.Errorf("claude-mem prereq incomplete: %+v", cm)
	}
}
