// Package dockerfile assembles a deterministic Dockerfile from a resolved
// Spec. Same input → byte-identical output, which is what enables:
//
//   - `vibrate build-dockerfile FILE` for inspection / debugging
//   - golden-file tests for regression detection
//   - image-tag fingerprints based on the generated content
//
// The Dockerfile has five logical stages:
//
//   1. base     — Ubuntu 24.04 LTS + always-on substrate (jq, rg, vim, ...)
//   2. features — per-feature install fragments from internal/feature
//   3. harness  — per-harness install from internal/harness
//   4. catalog  — per-entry install snippets from catalog markdown
//   5. runtime  — user setup, labels, CMD
//
// All five stages target the same final image; we use multi-stage tagging
// for clarity in `docker history` and to give layer-cache invalidation
// natural boundaries (feature changes don't rebuild the base toolkit).
package dockerfile

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/wlame/vibrator/internal/catalog"
	"github.com/wlame/vibrator/internal/feature"
	"github.com/wlame/vibrator/internal/harness"
)

// Spec is the fully-resolved input to the generator. Every field is
// expected to be pre-validated by the caller (CLI / wizard).
type Spec struct {
	// Harness identifies which agent harness gets installed in Stage 3.
	Harness harness.Harness

	// Profile is the named profile the user picked. Informational only —
	// included in the header comment so the generated file documents
	// itself, but not in the layer-content (which is feature-driven).
	Profile string

	// Shell is the default user shell inside the container.
	Shell string

	// Features is the resolved feature list, in Registry order (deps first).
	Features []feature.Feature

	// CatalogEntries are the per-harness catalog selections, in stable
	// (alphabetical-by-ID) order.
	CatalogEntries []*catalog.Entry

	// Username for the unprivileged user inside the container.
	// Defaults to "vibrate" if empty.
	Username string

	// HostUID / HostGID are baked as build-args so file permissions on
	// bind-mounted workspace paths match the host caller.
	HostUID int
	HostGID int

	// VibratorVersion is stamped into a LABEL for traceability.
	VibratorVersion string
}

// supportedShells documents which Shell values the generator handles.
// Adding a new shell = adding an apt-get line in stageBase + a Cmd switch.
var supportedShells = map[string]struct{}{
	"bash": {},
	"zsh":  {},
	"fish": {},
}

// Generate emits the full Dockerfile as bytes. Returns an error on invalid
// spec (unknown shell, missing harness, …) — callers should treat any
// error as a programming bug and surface to the user.
func Generate(spec Spec) ([]byte, error) {
	if err := validate(spec); err != nil {
		return nil, err
	}

	var b bytes.Buffer
	writeHeader(&b, spec)
	writeBaseStage(&b, spec)
	writeFeaturesStage(&b, spec)
	writeHarnessStage(&b, spec)
	writeCatalogStage(&b, spec)
	writeRuntimeStage(&b, spec)

	return b.Bytes(), nil
}

func validate(spec Spec) error {
	if spec.Harness == nil {
		return fmt.Errorf("dockerfile: Spec.Harness is required")
	}
	if _, ok := supportedShells[spec.Shell]; !ok {
		return fmt.Errorf("dockerfile: unsupported shell %q (supported: bash, zsh, fish)", spec.Shell)
	}
	return nil
}

// writeHeader emits the leading comment block. Includes a reproducibility
// hint — the exact CLI invocation that would re-derive this spec.
func writeHeader(b *bytes.Buffer, spec Spec) {
	featureIDs := featureIDsCSV(spec.Features)
	catalogIDs := catalogIDsCSV(spec.CatalogEntries)

	b.WriteString("# Generated by vibrate ")
	b.WriteString(versionOrDev(spec.VibratorVersion))
	b.WriteString(" — do not edit by hand.\n")
	b.WriteString("#\n")
	fmt.Fprintf(b, "# Harness:  %s (%s)\n", spec.Harness.ID(), spec.Harness.Name())
	fmt.Fprintf(b, "# Profile:  %s\n", spec.Profile)
	fmt.Fprintf(b, "# Shell:    %s\n", spec.Shell)
	fmt.Fprintf(b, "# Features: %s\n", featureIDs)
	fmt.Fprintf(b, "# Catalog:  %s\n", catalogIDs)
	b.WriteString("#\n")
	b.WriteString("# Reproduce this Dockerfile with:\n")
	b.WriteString("#   vibrate build-dockerfile")
	fmt.Fprintf(b, " --harness=%s", spec.Harness.ID())
	fmt.Fprintf(b, " --profile=%s", spec.Profile)
	fmt.Fprintf(b, " --shell=%s", spec.Shell)
	if catalogIDs != "(none)" {
		fmt.Fprintf(b, " --catalog=%s", catalogIDs)
	}
	b.WriteString("\n\n")
}

// writeBaseStage emits Stage 1: Ubuntu LTS + always-on substrate. Apt-installs
// the small, universally-useful CLIs. Binary downloads (rg, fd) are pulled in
// later via Stage features so they don't pollute the base if disabled.
func writeBaseStage(b *bytes.Buffer, spec Spec) {
	b.WriteString(`# ============================================================================
# Stage 1 — base: Ubuntu 24.04 LTS + always-on substrate
# ============================================================================
FROM ubuntu:24.04 AS base

ENV DEBIAN_FRONTEND=noninteractive

# Apt cache layer — always-on CLIs that every profile gets. Kept small.
RUN apt-get update && apt-get install -y --no-install-recommends \
      ca-certificates curl wget \
      git gpg openssh-client \
      sudo vim less tree \
      jq sqlite3 dnsutils \
      unzip xz-utils \
      build-essential \
      locales \
`)
	// Append the user's chosen shell so it's installed in the base stage.
	// bash is already present on Ubuntu — listing it explicitly is harmless.
	fmt.Fprintf(b, "      %s \\\n", spec.Shell)
	b.WriteString(` && locale-gen en_US.UTF-8 \
 && rm -rf /var/lib/apt/lists/*

ENV LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 COLORTERM=truecolor

# uv tools install into /usr/local/bin so every user finds them on PATH.
ENV UV_TOOL_BIN_DIR=/usr/local/bin

# ripgrep — multi-arch binary release. Always-on.
RUN ARCH=$(dpkg --print-architecture) && \
    RG_VERSION="15.1.0" && \
    if [ "$ARCH" = "amd64" ]; then RG_TRIPLE="x86_64-unknown-linux-musl"; else RG_TRIPLE="aarch64-unknown-linux-gnu"; fi && \
    curl -fsSL "https://github.com/BurntSushi/ripgrep/releases/download/${RG_VERSION}/ripgrep-${RG_VERSION}-${RG_TRIPLE}.tar.gz" \
      -o rg.tar.gz && \
    tar -xzf rg.tar.gz --strip-components=1 -C /usr/local/bin/ "ripgrep-${RG_VERSION}-${RG_TRIPLE}/rg" && \
    rm rg.tar.gz && rg --version

# fd-find via apt (Ubuntu names the binary fdfind; we symlink to fd).
RUN apt-get update && apt-get install -y --no-install-recommends fd-find fzf \
 && ln -sf /usr/bin/fdfind /usr/local/bin/fd \
 && rm -rf /var/lib/apt/lists/*

`)
}

// writeFeaturesStage emits Stage 2: per-feature Dockerfile fragments.
// Features come in dep order from feature.Resolve (deps first).
func writeFeaturesStage(b *bytes.Buffer, spec Spec) {
	b.WriteString(`# ============================================================================
# Stage 2 — features
# ============================================================================
FROM base AS features

`)
	if len(spec.Features) == 0 {
		b.WriteString("# (no features enabled — minimal profile)\n\n")
		return
	}
	for _, f := range spec.Features {
		fmt.Fprintf(b, "# --- feature: %s (%s) ---\n", f.ID, f.Name)
		writeFragment(b, f.Dockerfile)
		b.WriteString("\n")
	}
}

// writeHarnessStage emits Stage 3: harness install.
func writeHarnessStage(b *bytes.Buffer, spec Spec) {
	b.WriteString(`# ============================================================================
# Stage 3 — harness install
# ============================================================================
FROM features AS harness

`)
	fmt.Fprintf(b, "# --- harness: %s (%s) ---\n", spec.Harness.ID(), spec.Harness.Name())
	writeFragment(b, spec.Harness.Dockerfile())
	b.WriteString("\n")
}

// writeCatalogStage emits Stage 4: catalog entry installs. Entries are
// processed in alphabetical ID order for deterministic output (the catalog
// loader doesn't impose order; we sort here).
func writeCatalogStage(b *bytes.Buffer, spec Spec) {
	b.WriteString(`# ============================================================================
# Stage 4 — catalog entries
# ============================================================================
FROM harness AS catalog

`)
	if len(spec.CatalogEntries) == 0 {
		b.WriteString("# (no catalog entries selected)\n\n")
		return
	}
	// Stable order so the same selection set always produces the same bytes.
	entries := append([]*catalog.Entry(nil), spec.CatalogEntries...)
	sort.Slice(entries, func(i, j int) bool { return entries[i].ID < entries[j].ID })

	for _, e := range entries {
		fmt.Fprintf(b, "# --- catalog/%s/%s (%s) ---\n", e.Harness, e.ID, e.Kind)
		if e.Source != "" {
			fmt.Fprintf(b, "# Source: %s\n", e.Source)
		}
		writeFragment(b, e.Install)
		b.WriteString("\n")
	}
}

// writeRuntimeStage emits Stage 5: user creation, labels, env, CMD.
// Vibrator-spec ARGs (USERNAME, HOST_UID, HOST_GID) are passed via
// `docker build --build-arg ...` in internal/docker so the same generated
// Dockerfile works for different hosts.
func writeRuntimeStage(b *bytes.Buffer, spec Spec) {
	username := spec.Username
	if username == "" {
		username = "vibrate"
	}

	b.WriteString(`# ============================================================================
# Stage 5 — runtime: unprivileged user, labels, default command
# ============================================================================
FROM catalog AS runtime

# Build args supply the host's UID/GID so file permissions on bind-mounted
# workspace paths match the caller (set by internal/docker at build time).
`)
	fmt.Fprintf(b, "ARG USERNAME=%s\n", username)
	fmt.Fprintf(b, "ARG HOST_UID=%d\n", spec.HostUID)
	fmt.Fprintf(b, "ARG HOST_GID=%d\n", spec.HostGID)

	b.WriteString(`
# Replace any existing user/group at the target UID/GID (Ubuntu ships an
# "ubuntu" user at 1000 which usually clashes with the host's first user).
RUN set -eux; \
    if EXISTING_USER=$(getent passwd ${HOST_UID} | cut -d: -f1); [ -n "$EXISTING_USER" ]; then userdel -r "$EXISTING_USER" 2>/dev/null || true; fi; \
    if EXISTING_GROUP=$(getent group ${HOST_GID} | cut -d: -f1); [ -n "$EXISTING_GROUP" ]; then groupdel "$EXISTING_GROUP" 2>/dev/null || true; fi; \
`)
	fmt.Fprintf(b, "    groupadd -g ${HOST_GID} ${USERNAME} && \\\n")
	fmt.Fprintf(b, "    useradd -m -s /bin/%s -u ${HOST_UID} -g ${HOST_GID} ${USERNAME} && \\\n", spec.Shell)
	b.WriteString(`    echo "${USERNAME} ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/${USERNAME} && \
    chmod 0440 /etc/sudoers.d/${USERNAME}

USER ${USERNAME}
WORKDIR /home/${USERNAME}

`)

	// Auth env-var ARGs — declared so they're listed in the image manifest
	// (`docker inspect`). Actual values are injected by `docker run -e ...`
	// at runtime, not baked into the image.
	if envs := spec.Harness.AuthEnvVars(); len(envs) > 0 {
		b.WriteString("# Auth env vars expected by this harness (forwarded by `docker run -e`):\n")
		for _, e := range envs {
			fmt.Fprintf(b, "ENV %s=\"\"\n", e)
		}
		b.WriteString("\n")
	}

	// Labels — used by `vibrate variants list` and image upgrade workflows.
	b.WriteString("# Labels — used by `vibrate variants list` and upgrade workflows.\n")
	fmt.Fprintf(b, "LABEL vibrator.version=%q\n", versionOrDev(spec.VibratorVersion))
	fmt.Fprintf(b, "LABEL vibrator.harness=%q\n", spec.Harness.ID())
	fmt.Fprintf(b, "LABEL vibrator.profile=%q\n", spec.Profile)
	fmt.Fprintf(b, "LABEL vibrator.shell=%q\n", spec.Shell)
	fmt.Fprintf(b, "LABEL vibrator.features=%q\n", featureIDsCSV(spec.Features))
	fmt.Fprintf(b, "LABEL vibrator.catalog=%q\n", catalogIDsCSV(spec.CatalogEntries))

	b.WriteString("\n")
	fmt.Fprintf(b, "CMD [\"/bin/%s\"]\n", spec.Shell)
}

// writeFragment appends a (possibly multi-line) fragment to the buffer with
// a single trailing newline. Trims excess trailing newlines so successive
// fragments don't accumulate blank lines.
func writeFragment(b *bytes.Buffer, frag string) {
	b.WriteString(strings.TrimRight(frag, "\n"))
	b.WriteByte('\n')
}

// featureIDsCSV formats feature IDs for header comments and labels.
// Returns "(none)" when the slice is empty so the header reads sensibly.
func featureIDsCSV(features []feature.Feature) string {
	if len(features) == 0 {
		return "(none)"
	}
	ids := make([]string, len(features))
	for i, f := range features {
		ids[i] = f.ID
	}
	return strings.Join(ids, ",")
}

// catalogIDsCSV formats catalog entry IDs for header comments and labels.
func catalogIDsCSV(entries []*catalog.Entry) string {
	if len(entries) == 0 {
		return "(none)"
	}
	// Sort for stability — same selection should always produce the same
	// CSV regardless of input order.
	ids := make([]string, len(entries))
	for i, e := range entries {
		ids[i] = e.ID
	}
	sort.Strings(ids)
	return strings.Join(ids, ",")
}

func versionOrDev(v string) string {
	if v == "" {
		return "dev"
	}
	return v
}
